{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "room",
    "query": {
     "query": "label_values(sensor_info, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Room",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_info{name=\"$room\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_light_lux{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_humidity_percentage{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_battery_status_percentage{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_info{name=\"$room\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_info{name=\"$room\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Signal Quality",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_bluetooth_signal_quality{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_info{name=\"$room\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_info{name=\"$room\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_up_since_gauge{name=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{name=\"$room\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sensor_humidity_percentage{name=\"$room\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sensor_battery_status_percentage{name=\"$room\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "sensor_light_lux{name=\"$room\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}